"""Enums for guideline information records."""

from __future__ import annotations

from enum import Enum


class FailureCode(str, Enum):
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    NETWORK_ERROR = "NETWORK_ERROR"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    RATE_LIMIT = "RATE_LIMIT"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"
    MODEL_REFUSAL = "MODEL_REFUSAL"
    JSON_PARSE_ERROR = "JSON_PARSE_ERROR"
    WIRE_RESPONSE_INVALID = "WIRE_RESPONSE_INVALID"
    RESPONSE_NORMALIZATION_ERROR = "RESPONSE_NORMALIZATION_ERROR"
    AMBIGUOUS_FIELD_SHAPE = "AMBIGUOUS_FIELD_SHAPE"
    CANONICAL_SCHEMA_VALIDATION_ERROR = "CANONICAL_SCHEMA_VALIDATION_ERROR"
    SPAN_VALIDATION_ERROR = "SPAN_VALIDATION_ERROR"
    ADAPTER_INTERNAL_ERROR = "ADAPTER_INTERNAL_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"


class ReviewStatus(str, Enum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    IN_REVIEW = "IN_REVIEW"
    SUBMITTED = "SUBMITTED"
    NEEDS_ADJUDICATION = "NEEDS_ADJUDICATION"
    ADJUDICATED = "ADJUDICATED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    INVALID_SOURCE = "INVALID_SOURCE"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class ReviewDecisionType(str, Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    EDIT = "EDIT"
    UNRESOLVED = "UNRESOLVED"


class ReviewOrigin(str, Enum):
    HUMAN = "HUMAN"
    SYNTHETIC_TEST = "SYNTHETIC_TEST"
    MIGRATED = "MIGRATED"


class RecommendationType(str, Enum):
    FORMAL_RECOMMENDATION = "FORMAL_RECOMMENDATION"
    GOOD_PRACTICE_STATEMENT = "GOOD_PRACTICE_STATEMENT"
    IMPLEMENTATION_REMARK = "IMPLEMENTATION_REMARK"
    RESEARCH_RECOMMENDATION = "RESEARCH_RECOMMENDATION"
    RATIONALE = "RATIONALE"
    EVIDENCE_SUMMARY = "EVIDENCE_SUMMARY"
    NOT_RECOMMENDATION = "NOT_RECOMMENDATION"
    UNRESOLVED = "UNRESOLVED"


class SourceType(str, Enum):
    EXPLICIT_IN_RECOMMENDATION = "EXPLICIT_IN_RECOMMENDATION"
    EXPLICIT_IN_CLINICAL_QUESTION = "EXPLICIT_IN_CLINICAL_QUESTION"
    EXPLICIT_IN_SECTION_HEADING = "EXPLICIT_IN_SECTION_HEADING"
    EXPLICIT_IN_NEARBY_CONTEXT = "EXPLICIT_IN_NEARBY_CONTEXT"
    MODEL_INFERRED = "MODEL_INFERRED"
    NOT_STATED = "NOT_STATED"


class SpanCoordinateSpace(str, Enum):
    SOURCE_BLOCK = "SOURCE_BLOCK"
    CANDIDATE_TEXT = "CANDIDATE_TEXT"
    CONTEXT_BEFORE = "CONTEXT_BEFORE"
    CONTEXT_AFTER = "CONTEXT_AFTER"
    SECTION_HEADING = "SECTION_HEADING"
    CLINICAL_QUESTION = "CLINICAL_QUESTION"


class SpanIssueCode(str, Enum):
    EXACT_MATCH = "EXACT_MATCH"
    NORMALIZATION_ONLY = "NORMALIZATION_ONLY"
    WHITESPACE_DIFFERENCE = "WHITESPACE_DIFFERENCE"
    UNICODE_DIFFERENCE = "UNICODE_DIFFERENCE"
    MARKDOWN_DIFFERENCE = "MARKDOWN_DIFFERENCE"
    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    SPAN_OUT_OF_RANGE = "SPAN_OUT_OF_RANGE"
    WRONG_SOURCE_BLOCK = "WRONG_SOURCE_BLOCK"
    WRONG_CONTEXT_SOURCE = "WRONG_CONTEXT_SOURCE"
    SOURCE_REVISION_MISMATCH = "SOURCE_REVISION_MISMATCH"
    PARTIAL_EVIDENCE = "PARTIAL_EVIDENCE"
    UNSUPPORTED_FIELD = "UNSUPPORTED_FIELD"
    OVER_INFERRED = "OVER_INFERRED"


class SpanSupportStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    INVALID_SPAN = "INVALID_SPAN"
    SOURCE_REVISION_MISMATCH = "SOURCE_REVISION_MISMATCH"


class RecommendedRoute(str, Enum):
    AUTO_ACCEPT = "AUTO_ACCEPT"
    RANDOM_AUDIT = "RANDOM_AUDIT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    ADJUDICATION = "ADJUDICATION"
    REJECT = "REJECT"


class SelectorName(str, Enum):
    RANDOM_AUDIT = "RandomAuditSelector"
    UNCERTAINTY = "UncertaintySelector"
    EXTRACTOR_VERIFIER_DISAGREEMENT = "ExtractorVerifierDisagreementSelector"
    RULE_MODEL_CONFLICT = "RuleModelConflictSelector"
    HARD_NEGATIVE = "HardNegativeSelector"
    MULTI_CLAIM = "MultiClaimSelector"
    FORMAT_STRATIFIED = "FormatStratifiedSelector"


class IssueCode(str, Enum):
    FALSE_POSITIVE_RECOMMENDATION = "FALSE_POSITIVE_RECOMMENDATION"
    FALSE_NEGATIVE_RECOMMENDATION = "FALSE_NEGATIVE_RECOMMENDATION"
    MISSED_RECOMMENDATION = "MISSED_RECOMMENDATION"
    BOUNDARY_TOO_SHORT = "BOUNDARY_TOO_SHORT"
    BOUNDARY_TOO_LONG = "BOUNDARY_TOO_LONG"
    WRONG_RECOMMENDATION_TYPE = "WRONG_RECOMMENDATION_TYPE"
    DIRECTION_ERROR = "DIRECTION_ERROR"
    STRENGTH_ERROR = "STRENGTH_ERROR"
    CERTAINTY_ERROR = "CERTAINTY_ERROR"
    POPULATION_ERROR = "POPULATION_ERROR"
    INTERVENTION_ERROR = "INTERVENTION_ERROR"
    DOSAGE_ERROR = "DOSAGE_ERROR"
    DURATION_ERROR = "DURATION_ERROR"
    CONDITION_ERROR = "CONDITION_ERROR"
    MULTI_CLAIM_NOT_SPLIT = "MULTI_CLAIM_NOT_SPLIT"
    UNSUPPORTED_FIELD = "UNSUPPORTED_FIELD"
    INVALID_EVIDENCE_SPAN = "INVALID_EVIDENCE_SPAN"
    WRONG_SOURCE_BLOCK = "WRONG_SOURCE_BLOCK"
    WRONG_CONTEXT_SOURCE = "WRONG_CONTEXT_SOURCE"
    SOURCE_REVISION_MISMATCH = "SOURCE_REVISION_MISMATCH"
    CONTEXT_LEAKAGE = "CONTEXT_LEAKAGE"
    OVER_INFERRED = "OVER_INFERRED"
    DUPLICATE_RECOMMENDATION = "DUPLICATE_RECOMMENDATION"
    JSON_PARSE_ERROR = "JSON_PARSE_ERROR"
    OTHER = "OTHER"


class AnnotationTier(str, Enum):
    SILVER_SINGLE_REVIEW = "SILVER_SINGLE_REVIEW"
    GOLD_DOUBLE_AGREEMENT = "GOLD_DOUBLE_AGREEMENT"
    GOLD_ADJUDICATED = "GOLD_ADJUDICATED"
