"""Rule-based clinical department classification for guideline metadata."""

from __future__ import annotations

import re
import unicodedata
from collections import Counter
from dataclasses import dataclass
from typing import Iterable


UNKNOWN_DEPARTMENT = "未分类"


@dataclass(frozen=True)
class DepartmentRule:
    department: str
    keywords: tuple[str, ...]
    title_bonus: int = 4
    text_weight: int = 1


DEPARTMENT_RULES: tuple[DepartmentRule, ...] = (
    DepartmentRule(
        "呼吸内科",
        (
            "respiratory",
            "pulmonary",
            "lung disease",
            "pneumonia",
            "asthma",
            "copd",
            "chronic obstructive pulmonary",
            "sleep apnea",
            "obstructive sleep apnea",
            "oxygen therapy",
            "ventilation",
            "tuberculosis respiratory",
            "bronchitis",
            "bronchiolitis",
            "呼吸",
            "肺炎",
            "哮喘",
            "慢阻肺",
            "睡眠呼吸暂停",
            "支气管炎",
        ),
    ),
    DepartmentRule(
        "消化内科",
        (
            "gastro",
            "digestive",
            "gastritis",
            "hepatitis",
            "cirrhosis",
            "liver disease",
            "inflammatory bowel",
            "crohn",
            "ulcerative colitis",
            "colitis",
            "diarrhea",
            "constipation",
            "pancreatitis",
            "gallstone",
            "gastrointestinal",
            "消化",
            "胃炎",
            "肝炎",
            "肝硬化",
            "肠炎",
            "炎症性肠病",
            "胰腺炎",
        ),
    ),
    DepartmentRule(
        "心血管内科",
        (
            "cardiovascular",
            "cardiac",
            "heart failure",
            "hypertension",
            "coronary",
            "arrhythmia",
            "atrial fibrillation",
            "myocardial infarction",
            "angina",
            "dyslipidemia",
            "cholesterol",
            "lipid",
            "心血管",
            "高血压",
            "冠心病",
            "心律失常",
            "心力衰竭",
            "心肌梗死",
        ),
    ),
    DepartmentRule(
        "神经内科",
        (
            "neurology",
            "neurologic",
            "stroke",
            "epilepsy",
            "seizure",
            "parkinson",
            "dementia",
            "multiple sclerosis",
            "migraine",
            "headache",
            "neuropathy",
            "脑卒中",
            "癫痫",
            "帕金森",
            "痴呆",
            "偏头痛",
            "神经病变",
        ),
    ),
    DepartmentRule(
        "内分泌科",
        (
            "diabetes",
            "diabetic",
            "insulin",
            "thyroid",
            "hyperthyroid",
            "hypothyroid",
            "osteoporosis",
            "endocrine",
            "obesity",
            "metabolic",
            "adrenal",
            "pituitary",
            "糖尿病",
            "甲亢",
            "甲减",
            "骨质疏松",
            "内分泌",
            "肥胖",
        ),
    ),
    DepartmentRule(
        "血液内科",
        (
            "hematology",
            "haematology",
            "leukemia",
            "leukaemia",
            "lymphoma",
            "myeloma",
            "anemia",
            "anaemia",
            "thrombocytopenia",
            "hemophilia",
            "haemophilia",
            "sickle cell",
            "白血病",
            "贫血",
            "血小板减少",
            "淋巴瘤",
            "骨髓瘤",
            "血友病",
        ),
    ),
    DepartmentRule(
        "肾内科",
        (
            "kidney disease",
            "renal",
            "nephrology",
            "nephritis",
            "nephrotic",
            "dialysis",
            "hemodialysis",
            "haemodialysis",
            "uremia",
            "chronic kidney",
            "acute kidney",
            "肾炎",
            "肾病",
            "尿毒症",
            "透析",
            "慢性肾脏病",
        ),
    ),
    DepartmentRule(
        "免疫科/风湿免疫科",
        (
            "rheumatology",
            "rheumatoid",
            "lupus",
            "systemic lupus",
            "arthritis",
            "spondyloarthritis",
            "vasculitis",
            "autoimmune",
            "sjogren",
            "gout",
            "类风湿",
            "红斑狼疮",
            "风湿",
            "免疫",
            "痛风",
        ),
    ),
    DepartmentRule(
        "感染内科",
        (
            "infectious",
            "infection",
            "sepsis",
            "antimicrobial",
            "antibiotic",
            "viral",
            "bacterial",
            "fungal",
            "hiv",
            "aids",
            "covid",
            "influenza",
            "tuberculosis",
            "hepatitis b",
            "hepatitis c",
            "感染",
            "乙肝",
            "结核",
            "败血症",
            "抗菌药",
            "新冠",
            "流感",
        ),
    ),
    DepartmentRule(
        "过敏/变态反应科",
        (
            "allergy",
            "allergic",
            "anaphylaxis",
            "atopic",
            "rhinitis",
            "urticaria",
            "hypersensitivity",
            "过敏",
            "变态反应",
            "过敏性鼻炎",
            "荨麻疹",
            "过敏反应",
        ),
    ),
    DepartmentRule(
        "老年病科",
        (
            "geriatric",
            "older people",
            "older adults",
            "elderly",
            "frailty",
            "老年",
            "衰弱",
        ),
    ),
    DepartmentRule(
        "普通外科",
        (
            "general surgery",
            "appendicitis",
            "hernia",
            "breast disease",
            "breast surgery",
            "thyroid surgery",
            "surgical site",
            "wound management",
            "阑尾炎",
            "疝气",
            "乳腺",
            "普外",
        ),
    ),
    DepartmentRule(
        "骨科",
        (
            "orthopedic",
            "orthopaedic",
            "fracture",
            "spine",
            "spinal",
            "joint replacement",
            "osteoarthritis",
            "low back pain",
            "back pain",
            "scoliosis",
            "骨折",
            "关节炎",
            "脊柱",
            "骨科",
            "腰痛",
        ),
    ),
    DepartmentRule(
        "泌尿外科",
        (
            "urology",
            "urologic",
            "urinary",
            "prostate",
            "renal stone",
            "kidney stone",
            "bladder",
            "incontinence",
            "benign prostatic",
            "肾结石",
            "前列腺",
            "膀胱",
            "泌尿",
        ),
    ),
    DepartmentRule(
        "胸外科",
        (
            "thoracic surgery",
            "lung cancer surgery",
            "esophageal cancer",
            "oesophageal cancer",
            "mediastinal",
            "pneumothorax",
            "肺癌",
            "食管癌",
            "胸外",
            "气胸",
        ),
    ),
    DepartmentRule(
        "心血管外科",
        (
            "cardiac surgery",
            "cardiothoracic surgery",
            "coronary artery bypass",
            "valve surgery",
            "aortic aneurysm",
            "vascular surgery",
            "心脏搭桥",
            "瓣膜",
            "主动脉瘤",
            "血管外科",
        ),
    ),
    DepartmentRule(
        "神经外科",
        (
            "neurosurgery",
            "brain tumor",
            "brain tumour",
            "intracranial",
            "subarachnoid",
            "brain hemorrhage",
            "brain haemorrhage",
            "脑肿瘤",
            "脑出血",
            "神经外科",
        ),
    ),
    DepartmentRule(
        "肝胆外科",
        (
            "hepatobiliary",
            "liver cancer surgery",
            "cholecystectomy",
            "bile duct",
            "gallbladder",
            "cholangiocarcinoma",
            "肝癌",
            "胆结石",
            "胆囊",
            "胆管",
            "肝胆",
        ),
    ),
    DepartmentRule(
        "肛肠外科",
        (
            "colorectal surgery",
            "hemorrhoid",
            "haemorrhoid",
            "anal fistula",
            "perianal",
            "rectal prolapse",
            "痔疮",
            "肛瘘",
            "肛肠",
        ),
    ),
    DepartmentRule(
        "器官移植",
        (
            "transplant",
            "transplantation",
            "organ donor",
            "immunosuppression after transplant",
            "器官移植",
            "移植",
        ),
    ),
    DepartmentRule(
        "烧伤科",
        (
            "burn",
            "burns",
            "scald",
            "烧伤",
            "烫伤",
        ),
    ),
    DepartmentRule(
        "妇科",
        (
            "gynecology",
            "gynaecology",
            "menstrual",
            "endometriosis",
            "menopause",
            "ovarian",
            "cervical",
            "uterine",
            "vaginal",
            "月经",
            "子宫内膜异位",
            "卵巢",
            "宫颈",
            "妇科",
        ),
    ),
    DepartmentRule(
        "产科",
        (
            "pregnancy",
            "pregnant",
            "antenatal",
            "prenatal",
            "postpartum",
            "postnatal",
            "labour",
            "labor and delivery",
            "obstetric",
            "obstetrics",
            "分娩",
            "产后",
            "孕检",
            "妊娠",
            "产科",
        ),
    ),
    DepartmentRule(
        "计划生育科",
        (
            "contraception",
            "contraceptive",
            "abortion",
            "family planning",
            "termination of pregnancy",
            "避孕",
            "流产",
            "计划生育",
        ),
    ),
    DepartmentRule(
        "生殖医学科",
        (
            "fertility",
            "infertility",
            "reproductive",
            "ivf",
            "assisted reproduction",
            "不孕",
            "生殖",
            "辅助生殖",
        ),
    ),
    DepartmentRule(
        "新生儿科",
        (
            "neonatal",
            "newborn",
            "preterm infant",
            "premature infant",
            "新生儿",
            "早产儿",
        ),
    ),
    DepartmentRule(
        "小儿呼吸科",
        (
            "pediatric asthma",
            "paediatric asthma",
            "children with asthma",
            "childhood asthma",
            "pediatric pneumonia",
            "paediatric pneumonia",
            "pediatric sleep apnea",
            "paediatric sleep apnea",
            "儿童哮喘",
            "儿童肺炎",
            "小儿呼吸",
        ),
    ),
    DepartmentRule(
        "小儿消化科",
        (
            "pediatric gastro",
            "paediatric gastro",
            "children with inflammatory bowel",
            "pediatric constipation",
            "paediatric constipation",
            "小儿消化",
            "儿童腹泻",
            "儿童便秘",
        ),
    ),
    DepartmentRule(
        "小儿外科",
        (
            "pediatric surgery",
            "paediatric surgery",
            "children undergoing surgery",
            "小儿外科",
        ),
    ),
    DepartmentRule(
        "小儿内科",
        (
            "pediatric",
            "paediatric",
            "child",
            "children",
            "infant",
            "toddler",
            "adolescent",
            "儿童",
            "小儿",
            "婴幼儿",
            "青少年",
        ),
        title_bonus=2,
    ),
    DepartmentRule(
        "耳鼻喉科",
        (
            "ear nose throat",
            "ent",
            "otolaryngology",
            "otitis",
            "sinusitis",
            "hearing loss",
            "tonsil",
            "larynx",
            "nasal",
            "rhinosinusitis",
            "耳鼻喉",
            "中耳炎",
            "鼻窦炎",
            "听力",
            "扁桃体",
        ),
    ),
    DepartmentRule(
        "眼科",
        (
            "ophthalmology",
            "eye",
            "glaucoma",
            "cataract",
            "retinopathy",
            "macular",
            "visual",
            "conjunctivitis",
            "眼科",
            "青光眼",
            "白内障",
            "视网膜",
            "黄斑",
        ),
    ),
    DepartmentRule(
        "口腔科",
        (
            "dental",
            "dentistry",
            "oral health",
            "periodontal",
            "caries",
            "tooth",
            "teeth",
            "口腔",
            "牙",
            "龋齿",
            "牙周",
        ),
    ),
    DepartmentRule(
        "皮肤性病科",
        (
            "dermatology",
            "skin",
            "eczema",
            "psoriasis",
            "acne",
            "sexually transmitted",
            "syphilis",
            "gonorrhea",
            "chlamydia",
            "皮肤",
            "湿疹",
            "银屑病",
            "痤疮",
            "性病",
            "梅毒",
            "淋病",
        ),
    ),
    DepartmentRule(
        "肿瘤科",
        (
            "cancer",
            "carcinoma",
            "tumor",
            "tumour",
            "oncology",
            "chemotherapy",
            "radiotherapy",
            "neoplasm",
            "malignancy",
            "malignant",
            "sarcoma",
            "肿瘤",
            "癌",
            "化疗",
            "放疗",
            "恶性",
        ),
    ),
    DepartmentRule(
        "精神心理科",
        (
            "mental health",
            "psychiatry",
            "psychological",
            "depression",
            "anxiety",
            "schizophrenia",
            "bipolar",
            "autism",
            "adhd",
            "substance use",
            "addiction",
            "insomnia",
            "sleep disorder",
            "精神",
            "心理",
            "抑郁",
            "焦虑",
            "精神分裂",
            "自闭症",
            "失眠",
        ),
    ),
    DepartmentRule(
        "整形美容科",
        (
            "plastic surgery",
            "cosmetic",
            "aesthetic",
            "reconstructive surgery",
            "整形",
            "美容",
        ),
    ),
    DepartmentRule(
        "康复医学科",
        (
            "rehabilitation",
            "physiotherapy",
            "physical therapy",
            "occupational therapy",
            "speech therapy",
            "康复",
            "物理治疗",
        ),
    ),
    DepartmentRule(
        "营养科",
        (
            "nutrition",
            "diet",
            "dietary",
            "malnutrition",
            "enteral feeding",
            "parenteral nutrition",
            "营养",
            "膳食",
            "饮食",
        ),
    ),
)


def _contains_keyword(text: str, keyword: str) -> bool:
    key = keyword.lower()
    if re.search(r"[\u4e00-\u9fff]", key):
        return key in text
    return re.search(rf"(?<![a-z0-9]){re.escape(key)}(?![a-z0-9])", text) is not None


def _normalize_text(text: str) -> str:
    return unicodedata.normalize("NFKC", text or "").lower()


def classify_clinical_department(title: str = "", abstract: str = "", content: str = "") -> str:
    """Return the best department label for a guideline-like document."""

    title_text = _normalize_text(title)
    body_text = _normalize_text(f"{abstract or ''}\n{(content or '')[:12000]}")
    scores: Counter[str] = Counter()
    for rule in DEPARTMENT_RULES:
        for keyword in rule.keywords:
            if _contains_keyword(title_text, keyword):
                scores[rule.department] += rule.title_bonus
            if _contains_keyword(body_text, keyword):
                scores[rule.department] += rule.text_weight
    if not scores:
        return UNKNOWN_DEPARTMENT
    department, score = scores.most_common(1)[0]
    return department if score > 0 else UNKNOWN_DEPARTMENT


def allowed_departments() -> Iterable[str]:
    return [rule.department for rule in DEPARTMENT_RULES] + [UNKNOWN_DEPARTMENT]
