"""存储层文件：定义 PostgreSQL schema、行映射、入库流程和完整性检查。

阅读本文件时，先看模块入口函数和被谁调用，再看具体规则或数据结构。
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from src.common.process_jsonl import write_jsonl
from src.storage.connection import DATABASE_URL, connection, get_connection
from src.storage.contract_check import build_storage_contract_report
from src.storage.generic_ingest import GENERIC_TABLE_CONFIG, ingest_table, ingest_tables_atomically, integrity_report, table_counts
from src.storage.repositories.cleaned_records import (
    ingest_cleaned_records,
    insert_cleaned_records,
    insert_guidelines,
    insert_papers,
)
from src.storage.row_mappers import cleaned_record_row, guideline_row, paper_row
from src.storage.schema import SCHEMA_TABLES, create_indexes as _create_indexes, create_schema
from src.storage.utils import (
    DEFAULT_BATCH_SIZE,
    as_int as _as_int,
    batches as _batches,
    execute_many as _execute_many,
    iter_jsonl,
    json_list as _json_list,
    json_obj as _json,
    sql_identifier as _sql_identifier,
)


def main() -> None:
    """PostgreSQL 存储层命令行入口。"""

    # 这个 CLI 只负责 schema、contract check 和入库，不负责判断候选是否应该发布。
    # 正式发布筛选应在 pipeline.publish.release_exporter 之前完成。
    parser = argparse.ArgumentParser(description="PostgreSQL storage for the Living-Guideline knowledge base.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Create Living-Guideline PostgreSQL schema")
    init_parser.add_argument("--recreate", action="store_true", help="Drop and recreate all Living-Guideline tables")

    cleaned_parser = subparsers.add_parser("ingest-cleaned", help="Ingest source_cleaner JSONL output")
    cleaned_parser.add_argument("--input", required=True, help="Cleaned JSONL path")
    cleaned_parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)

    table_parser = subparsers.add_parser("ingest-table", help="Ingest a schema_v2 table JSONL")
    table_parser.add_argument("--table", required=True, choices=sorted(GENERIC_TABLE_CONFIG))
    table_parser.add_argument("--input", required=True)
    table_parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)

    release_parser = subparsers.add_parser("ingest-release", help="Ingest a publish_ready_v1 release package in FK order")
    release_parser.add_argument("--release-dir", required=True, help="Directory generated by src.pipeline.publish.release_exporter")
    release_parser.add_argument("--recreate", action="store_true", help="Drop and recreate Living-Guideline tables first")
    release_parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)

    validate_parser = subparsers.add_parser("validate-run", help="Validate a reviewed run directory against storage ingest contract")
    validate_parser.add_argument("--run-dir", required=True, help="Reviewed run directory containing storage JSONL files")
    validate_parser.add_argument("--output", help="Optional JSONL report path")

    subparsers.add_parser("counts", help="Print row counts for all Living-Guideline tables")
    subparsers.add_parser("integrity-report", help="Print storage integrity counts and orphan checks")

    args = parser.parse_args()
    if args.command == "init":
        create_schema(recreate=args.recreate)
    elif args.command == "ingest-cleaned":
        total = ingest_cleaned_records(args.input, batch_size=args.batch_size)
        print(f"Done. Ingested {total} cleaned records.")
    elif args.command == "ingest-table":
        total = ingest_table(args.table, args.input, batch_size=args.batch_size)
        print(f"Done. Ingested {total} rows into {args.table}.")
    elif args.command == "ingest-release":
        summary = ingest_release_package(args.release_dir, recreate=args.recreate, batch_size=args.batch_size)
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    elif args.command == "validate-run":
        report = build_storage_contract_report(args.run_dir)
        if args.output:
            write_jsonl(args.output, [report])
        print(json.dumps(report, ensure_ascii=False, indent=2))
    elif args.command == "counts":
        print(json.dumps(table_counts(), ensure_ascii=False, indent=2))
    elif args.command == "integrity-report":
        print(json.dumps(integrity_report(), ensure_ascii=False, indent=2))


__all__ = [
    "DATABASE_URL",
    "DEFAULT_BATCH_SIZE",
    "GENERIC_TABLE_CONFIG",
    "SCHEMA_TABLES",
    "_as_int",
    "_batches",
    "_create_indexes",
    "_execute_many",
    "_json",
    "_json_list",
    "_sql_identifier",
    "cleaned_record_row",
    "connection",
    "create_schema",
    "build_storage_contract_report",
    "get_connection",
    "guideline_row",
    "ingest_cleaned_records",
    "ingest_release_package",
    "ingest_table",
    "ingest_tables_atomically",
    "integrity_report",
    "insert_cleaned_records",
    "insert_guidelines",
    "insert_papers",
    "iter_jsonl",
    "main",
    "paper_row",
    "table_counts",
]


def ingest_release_package(release_dir: str, *, recreate: bool = False, batch_size: int = DEFAULT_BATCH_SIZE) -> dict[str, int]:
    """Ingest a publish_ready release package in the order required by PostgreSQL FKs."""

    release_path = Path(release_dir)
    create_schema(recreate=recreate)
    summary: dict[str, int] = {}
    cleaned_path = release_path / "cleaned_records.jsonl"
    if cleaned_path.exists():
        summary["cleaned_records"] = ingest_cleaned_records(cleaned_path, batch_size=batch_size)

    # 入库顺序必须跟外键依赖一致：先 trace/PICO/候选，再版本和当前态，最后证据链接与 update logs。
    for table in [
        "model_traces",
        "pico_questions",
        "recommendation_candidates",
        "grade_candidates",
        "recommendation_versions",
        "recommendations",
        "evidence_items",
        "recommendation_version_evidence_links",
        "update_logs",
    ]:
        path = release_path / f"{table}.jsonl"
        if path.exists():
            summary[table] = ingest_table(table, path, batch_size=batch_size)
    return summary


if __name__ == "__main__":
    main()

